// This file is autogenerated by scripts/build-registry-index.ts
// Do not edit this file directly.
export const Index = {
	"button-demo": {
		files: ["../lib/registry/examples/button-demo.svelte"],
	},
};
