// This file is generated by Velite

export { default as gettingStarted } from './gettingStarted.json' with { type: 'json' }
export { default as components } from './components.json' with { type: 'json' }